var namespaceterravital__admin__edificios_1_1_bll_1_1_factory_services_1_1_u_o_w =
[
    [ "Interfaces", "namespaceterravital__admin__edificios_1_1_bll_1_1_factory_services_1_1_u_o_w_1_1_interfaces.html", "namespaceterravital__admin__edificios_1_1_bll_1_1_factory_services_1_1_u_o_w_1_1_interfaces" ],
    [ "Repositories", "namespaceterravital__admin__edificios_1_1_bll_1_1_factory_services_1_1_u_o_w_1_1_repositories.html", "namespaceterravital__admin__edificios_1_1_bll_1_1_factory_services_1_1_u_o_w_1_1_repositories" ]
];